version: "3"
services:
  billingservice:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    ports:
      - 5002:5002
  inventoryservice:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    ports:
      - 5000:5000
  shippingservice:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    ports:
      - 5002:5002
  usersservice:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    ports:
      - 5006:5006
